// Aoiro — 使い方 / 使用方法 / How to use: a complete walkthrough for someone who has never used the app and knows
// no accounting. Shown on the first page of the menu. Plain data: chapters → items (heading, text, steps, a page to
// open, a small table). **bold** is allowed in text. Exposes window.GUIDE.
window.GUIDE = {
  zh: {
    title: "使用方法：從零開始的完整攻略",
    lead: "不懂會計也沒關係。照這一頁從上往下做，就能從第一張收據一路走到確定申告。帳怎麼記、稅怎麼算，大部分都由 App 自動處理；你要做的是拍收據、確認，以及每年報一次稅。",
    year: { title: "一年的流程", rows: [["每天", "拍收據、開請款單（第 3 章）"], ["每月一次", "匯入銀行・信用卡明細、看待辦事項、下載備份（第 4 章）"], ["12 月〜1 月", "年底結帳：固定資產、資產負債表、檢查清單（第 5 章）"], ["2/16〜3/15", "確定申告；消費稅到 3/31（第 6 章）"]] },
    chapters: [
      { id: "basics", title: "會計超入門（5 分鐘）", time: "先讀一次就好", lead: "只要懂這幾個詞，就能看懂這個 App 的每一頁。",
        items: [
          { h: "為什麼要記帳？", p: ["個人事業主每年要向稅務署申報「今年賺了多少」。稅金是依照「營收 − 經費 = 所得」計算的，所以要把每一筆收入和支出記下來，這就是記帳。記得越完整，能列的經費越多，稅就越少。"] },
          { h: "營收・經費・所得", table: [["營收（売上）", "工作賺進來的錢，例如設計費、銷售款"], ["經費（経費）", "為了工作花的錢，例如電腦周邊、車資、電信費"], ["所得", "營收 − 經費。稅金依這個數字計算"]] },
          { h: "仕訳：一筆交易的兩面", p: ["每一筆交易都有兩面：錢花到哪裡（左邊，借方）、錢從哪裡來（右邊，貸方）。例如用自己的錢買了 1,100 円的文具：左邊「消耗品費 1,100」、右邊「事業主借 1,100」。", "**這些 App 都會自動做好**，你只要確認科目對不對。"] },
          { h: "事業主借・事業主貸", p: ["個人事業主的錢和私人的錢常常混在一起。用私人的錢或私人信用卡付工作支出時，記為「事業主借」（向自己借，不用還）；把事業的錢拿去當生活費時，記為「事業主貸」。沒有事業專用信用卡的人，大部分收據的付款方式都是「事業主借」，這也是 App 的預設值。"] },
          { h: "家事按分", p: ["在家工作時，房租、電費、網路費一部分是工作用、一部分是生活用。只把工作的比例列為經費，例如房租 30%。在 App 裡填「事業比例」就好；同一家店下次會自動帶入同樣比例。"] },
          { h: "固定資產與折舊", p: ["10 萬円以上、可以用好幾年的東西（電腦、相機等）不能一次全部列經費，要分好幾年列，這叫折舊。App 會提醒你登錄並自動計算。青色申告的話，未滿 30 萬円可以選擇當年一次列完（少額減價償却資產的特例）。"] },
          { h: "青色申告", p: ["事先向稅務署提出「青色申告承認申請書」的人，用複式簿記記帳並以 e-Tax 申報，最多可以從所得扣掉 65 萬円（青色申告特別扣除），稅會少很多。這個 App 就是照青色申告 65 萬円的要求設計的。"] },
          { h: "消費稅與インボイス", p: ["營收 1,000 萬円以下、而且沒有做インボイス（適格請求書發行事業者）登錄的人是「免稅事業者」，不用申報消費稅。有登錄的人要申報；2026 年度以前大多可以用「2 割特例」，只繳營收消費稅的 2 成。收據上的「T＋13 位數」就是對方的登錄番號。"] },
          { h: "收據要保存 7 年", p: ["拍照後，紙本收據仍建議保存 7 年。電子收據（PDF、網購明細）照樣用這個 App 存起來即可。"] },
        ] },
      { id: "setup", title: "最初的設定（只做一次，約 10 分鐘）", time: "第一天",
        items: [
          { h: "1. 建立帳號、登入", steps: ["在登入畫面輸入電子郵件和 8 個字元以上的密碼。", "按「還沒有帳號？建立一個」。之後都用同一組登入。", "手機用瀏覽器的「加入主畫面」，就能像 App 一樣打開。"] },
          { h: "2. 回答初始設定的 6 個問題", p: ["第一次登入會自動出現。每題都有白話說明，不確定就選建議的選項，之後隨時可以在「設定」→「重新初始設定」修改。"], steps: ["屋號或姓名。", "申報方式：已提出青色申告承認申請書並用 e-Tax 的話選「青色 65 萬円」。", "消費稅：沒有做インボイス登錄就選「免稅事業者」。", "工作支出怎麼付：用私人的錢或信用卡就選第一個（事業主借）。", "是否在家工作：是的話，房租等會提醒你按比例列經費。", "開始記帳那年 1 月 1 日的餘額：沒有事業專用帳戶就填 0。"], go: "settings" },
          { h: "3. 登錄每個月固定的支出", p: ["房租、手機費、網路費、訂閱服務等每月一樣的支出，登錄一次就會每月自動記帳。"], go: "entry", goLabel: "取引登錄頁最下方「固定支出」" },
          { h: "4. 有開請款單的人：填開立人資料", p: ["在「請款單」頁最下方填姓名、登錄番號、地址、匯款帳戶，請款單上才會印出來。"], go: "invoices" },
        ] },
      { id: "daily", title: "每天要做的事（每次 1 分鐘）", time: "有收支的時候",
        items: [
          { h: "花錢的時候：拍收據", steps: ["打開「收據」，按「拍照」拍下收據（也可以選照片、PDF，一次很多張）。", "App 會讀出日期、店名、金額、稅率和登錄番號，並建議科目。", "確認這 5 件事：日期、金額、科目、付款方式（私人的錢＝事業主借）、事業比例（私人也有用的東西要調低）。", "按「確認入帳」。"], go: "scan" },
          { h: "看到提醒時", table: [["10 萬円以上的設備", "按按鈕登錄為固定資產"], ["可能重複", "同一張收據拍了兩次的話，按「移除」"], ["和明細匯入的記帳相符", "保持勾選，收據會附到那筆記帳，不會記兩次"], ["顏色標記的欄位", "讀取把握度低，點一下確認收據上的位置"]] },
          { h: "沒有收據的支出", p: ["例如電車車資、自動扣款的訂閱。到「取引登錄」選「經費」，輸入日期、金額、交易對象、內容，下方會即時顯示記帳內容。選科目時下方會出現說明，不知道選哪個就看那裡。"], go: "entry" },
          { h: "賺錢的時候：開請款單或記營收", steps: ["向客戶請款：到「請款單」按「新增請款單」，填品項和金額，按「列印・PDF」寄給客戶，再按「開立並記帳營收」。", "收到錢時：打開那張請款單，輸入入帳日和實際金額，按「記帳收款」。", "現場收到現金：到「取引登錄」選「營收」記一筆。"], go: "invoices" },
        ] },
      { id: "monthly", title: "每月要做的事（約 15 分鐘）", time: "每月月初",
        items: [
          { h: "1. 匯入銀行和信用卡明細", steps: ["從網路銀行或信用卡網站下載上個月的 CSV。", "到「明細匯入」選種類和付款帳戶（私人信用卡＝事業主借），選檔案。", "已經記過的會顯示「相符」，不會重複；只把「未記帳」中屬於工作的勾起來，確認科目後按「記帳勾選的 N 筆」。", "ATM 提款、稅金、卡費扣款這類私人款項不用記。"], go: "bank" },
          { h: "2. 看儀表板的待辦事項", p: ["例如：等待確認的固定支出、10 萬円以上要確認的經費、沒填交易對象的經費、逾期的請款單。按「開啟」就會帶你到要處理的地方。"], go: "summary" },
          { h: "3. 下載備份", p: ["到「設定」按「下載備份」，把檔案存到雲端硬碟或電腦。超過一個月沒備份，待辦事項會提醒你。"], go: "settings" },
        ] },
      { id: "yearend", title: "年底要做的事（12 月〜隔年 1 月）", time: "約 1 小時",
        items: [
          { h: "1. 年底結帳檢查清單", p: ["打開「決算書・申報準備」，最上面有 10 個項目，由上往下確認。標「自動」的會依帳簿自動打勾。"], go: "filing" },
          { h: "2. 固定資產", p: ["今年買的 10 萬円以上的電腦、相機等，按「＋ 登錄固定資產」。折舊會自動計算並記入經費。"], go: "filing" },
          { h: "3. 資產負債表（青色 65 萬・55 萬円的人）", steps: ["12 月 31 日的餘額會自動算好，不用輸入。", "看一下存摺和手邊現金：一樣的話不用做任何事；不同的話在「實際餘額」填實際數字。", "下方出現「借貸平衡 ✓」就完成了。今年的期末餘額會自動成為明年的期初餘額。"], go: "filing" },
          { h: "4. 申告前檢查", p: ["頁面最下面會列出要修正（紅）、要確認（黃）、參考（藍）的項目。紅色要先改好；按「顯示相關記帳」會直接列出那幾筆。"], go: "filing" },
        ] },
      { id: "return", title: "確定申告（2 月 16 日〜3 月 15 日）", time: "約 1〜2 小時",
        items: [
          { h: "先準備好", table: [["個人番號卡（My Number 卡）和密碼", "用 e-Tax 送出時需要"], ["國民年金、國民健康保險的繳費證明", "社會保險費扣除"], ["人壽保險、地震保險的扣除證明書", "保險費扣除"], ["醫療費收據、故鄉納稅的收據", "醫療費扣除、捐款扣除"], ["支付調書或報酬明細（有被預扣稅時）", "源泉徵收稅額"]] },
          { h: "1. 在「確定申告導覽」輸入扣除項目", p: ["照證明書上的金額輸入，頁面會即時算出要繳或可以退的稅，以及住民稅、個人事業稅的預估。"], go: "return" },
          { h: "2. 用 e-Tax 抄寫表填作成コーナー", steps: ["在「確定申告導覽」頁按「開啟確定申告書等作成コーナー」。", "選「作成開始」→ e-Tax（個人番號卡）→「決算書・收支內譯書」。", "照 App 的「抄寫表」由上往下輸入，每個數字旁的「複製」可以直接貼上。", "決算書存好後進入「所得稅」，輸入扣除項目，最後確認所得金額和 App 一致。", "用個人番號卡送出；繳稅建議用振替納稅（帳戶自動扣款）。"], go: "return" },
          { h: "3. 消費稅（有做インボイス登錄的人）", p: ["到「消費稅申報」回答 3 個問題，App 會比較各種申報方式。上方若提示「改用某方式可以少繳」，按「改用這個方式」，再照下方步驟在作成コーナー申報。期限是 3 月 31 日。"], go: "ctax" },
          { h: "4. 把期限加進行事曆", p: ["儀表板「接下來的期限」按「加入行事曆（.ics）」，報稅、繳稅、住民稅、個人事業稅的日期都會加進手機行事曆，前 7 天和前 1 天提醒。"], go: "summary" },
        ] },
      { id: "help", title: "遇到問題時", time: "需要時",
        items: [
          { h: "常見問題", table: [["讀錯金額或日期", "確認畫面直接修改；已入帳的到仕訳帳點那一筆修改"], ["不知道選哪個科目", "選科目時下方有說明；「取引登錄」頁最下面有完整的科目說明"], ["收據上沒有登錄番號", "對方是免稅事業者時沒有；用 2 割特例或簡易課稅的話不影響稅額"], ["畫面上方出現「會計核心是舊版本」", "在 Supabase 的 SQL Editor 執行 supabase/002_accounting_core.sql"], ["換了手機", "用同一個帳號登入即可看到全部資料"], ["稅額和作成コーナー不一樣", "App 的稅額是預估，以作成コーナー為準"]] },
          { h: "提醒", p: ["App 的稅額都是預估，正式金額以國稅廳作成コーナー的計算為準。個別情況請參考國稅廳說明或洽詢稅理士。"] },
        ] },
    ],
  },
  ja: {
    title: "使い方：ゼロから始める完全ガイド",
    lead: "会計の知識がなくても大丈夫です。このページを上から順に進めれば、最初のレシートから確定申告までたどり着けます。仕訳や税金の計算はほとんどアプリが自動で行います。あなたがするのは、レシートを撮って確認すること、そして年に一度の申告だけです。",
    year: { title: "1年の流れ", rows: [["毎日", "レシートを撮る・請求書を出す（3章）"], ["月に1回", "銀行・カード明細の取込、やることリスト、バックアップ（4章）"], ["12月〜1月", "年末の決算：固定資産・貸借対照表・チェックリスト（5章）"], ["2/16〜3/15", "確定申告。消費税は3/31まで（6章）"]] },
    chapters: [
      { id: "basics", title: "会計のきほん（5分）", time: "最初に一度だけ", lead: "この言葉がわかれば、アプリのどのページも読めます。",
        items: [
          { h: "なぜ帳簿をつけるの？", p: ["個人事業主は毎年「今年いくら稼いだか」を税務署に申告します。税金は「売上 − 経費 = 所得」で計算されるので、お金の出入りをすべて記録します。これが記帳です。きちんと記録するほど経費を漏れなく入れられ、税金が少なくなります。"] },
          { h: "売上・経費・所得", table: [["売上", "仕事で入ってきたお金（制作料、販売代金など）"], ["経費", "仕事のために使ったお金（パソコン周辺機器、交通費、通信費など）"], ["所得", "売上 − 経費。税金はこの金額から計算します"]] },
          { h: "仕訳：取引の両面", p: ["取引には必ず二つの面があります。お金を何に使ったか（左・借方）と、どこから出たか（右・貸方）。例えば自分のお金で文房具を1,100円買ったら、左に「消耗品費 1,100」、右に「事業主借 1,100」。", "**これはアプリが自動で作ります。** あなたは科目が合っているかを確認するだけです。"] },
          { h: "事業主借・事業主貸", p: ["個人のお金や個人のカードで仕事の支払いをしたら「事業主借」（自分から借りた扱いで、返す必要はありません）。事業のお金を生活費に使ったら「事業主貸」。事業用のカードがない人は、ほとんどのレシートの支払方法が「事業主借」になり、アプリの初期値もそうなっています。"] },
          { h: "家事按分", p: ["自宅で仕事をしている場合、家賃や電気代、ネット代の一部は仕事用、一部は生活用です。仕事で使う割合だけを経費にします（例：家賃30%）。アプリでは「事業割合」に入れるだけ。同じお店は次回から同じ割合が入ります。"] },
          { h: "固定資産と減価償却", p: ["10万円以上で何年も使うもの（パソコン、カメラなど）は、買った年に全額を経費にできず、何年かに分けて経費にします。これが減価償却です。アプリが登録を促し、自動で計算します。青色申告なら30万円未満は一度に経費にできる特例があります。"] },
          { h: "青色申告", p: ["事前に「青色申告承認申請書」を出し、複式簿記で記帳して e-Tax で申告すると、所得から最大65万円を差し引けます（青色申告特別控除）。このアプリは青色申告65万円の条件に合わせて作られています。"] },
          { h: "消費税とインボイス", p: ["売上1,000万円以下でインボイス登録をしていなければ「免税事業者」で、消費税の申告はいりません。登録した人は申告が必要で、2026年分までは多くの場合「2割特例」（売上の消費税の2割だけ納める）が使えます。レシートの「T＋13桁」がお店の登録番号です。"] },
          { h: "領収書は7年保存", p: ["撮影したあとも紙の領収書は7年間保存しておくと安心です。電子の領収書（PDF、ネットの明細）はこのアプリに保存すれば大丈夫です。"] },
        ] },
      { id: "setup", title: "最初の設定（1回だけ・約10分）", time: "初日",
        items: [
          { h: "1. アカウントを作ってログイン", steps: ["ログイン画面でメールアドレスと8文字以上のパスワードを入力します。", "「アカウントを作成」を押します。次からは同じものでログインします。", "スマホはブラウザの「ホーム画面に追加」で、アプリのように開けます。"] },
          { h: "2. 初期設定の6つの質問に答える", p: ["初回ログインで自動的に表示されます。わからないときはおすすめを選べば大丈夫。あとから「設定」→「初期設定をやり直す」で変えられます。"], steps: ["屋号または氏名。", "申告の方法：青色申告承認申請書を出していて e-Tax なら「青色65万円」。", "消費税：インボイス登録をしていなければ「免税事業者」。", "支払い方法：個人のお金・カードなら一番上（事業主借）。", "自宅で仕事：はいなら家賃などの按分を案内します。", "帳簿を始める年の1月1日の残高：事業用口座がなければ0。"], go: "settings" },
          { h: "3. 毎月決まった支払いを登録", p: ["家賃・携帯代・ネット代・サブスクなど毎月同じ支払いは、一度登録すれば毎月自動で記帳されます。"], go: "entry", goLabel: "取引登録ページ下の「定期取引」" },
          { h: "4. 請求書を出す人：発行者情報を入力", p: ["「請求書」ページの一番下で、氏名・登録番号・住所・振込先を入れておくと請求書に印字されます。"], go: "invoices" },
        ] },
      { id: "daily", title: "毎日やること（1回1分）", time: "お金が動いたとき",
        items: [
          { h: "お金を使ったら：レシートを撮る", steps: ["「領収書」を開いて「撮影する」でレシートを撮ります（写真やPDFをまとめて選ぶこともできます）。", "日付・店名・金額・税率・登録番号を読み取り、科目を提案します。", "5つを確認：日付、金額、科目、支払方法（個人のお金＝事業主借）、事業割合（私用でも使うものは下げる）。", "「確定して記帳」を押します。"], go: "scan" },
          { h: "お知らせが出たら", table: [["10万円以上の備品", "ボタンから固定資産に登録"], ["重複の可能性", "同じレシートを2回撮ったなら「削除」"], ["明細で記帳済みの取引と一致", "チェックのままにすると、その記帳に領収書を付けます（二重になりません）"], ["色が付いた欄", "読み取りに自信がない欄。タップしてレシート上の位置を確認"]] },
          { h: "レシートのない支払い", p: ["電車代や自動引落しのサブスクなど。「取引登録」で「経費」を選び、日付・金額・取引先・内容を入れると、下に仕訳がすぐ表示されます。科目を選ぶと下に説明が出るので、迷ったらそこを見てください。"], go: "entry" },
          { h: "お金が入ったら：請求書か売上の記帳", steps: ["お客さまに請求：「請求書」で「新しい請求書」→品目と金額→「印刷・PDF」で送付→「発行して売上を記帳」。", "入金されたら：その請求書を開き、入金日と実際の金額を入れて「入金を記帳」。", "その場で現金をもらった：「取引登録」で「売上」を記帳。"], go: "invoices" },
        ] },
      { id: "monthly", title: "毎月やること（約15分）", time: "月のはじめ",
        items: [
          { h: "1. 銀行とカードの明細を取り込む", steps: ["ネットバンキングやカード会社のサイトで先月分のCSVをダウンロード。", "「明細取込」で種類と支払った口座（個人カード＝事業主借）を選び、ファイルを選択。", "記帳済みは「一致」と表示され二重になりません。「未記帳」のうち仕事のものだけにチェックし、科目を確認して記帳。", "ATM引出し・税金・カード引落しなど私的なものは記帳しません。"], go: "bank" },
          { h: "2. ダッシュボードの「やること」を見る", p: ["確認待ちの定期取引、10万円以上の経費、取引先が空欄の経費、期限を過ぎた請求書など。「開く」で対応する場所に移動します。"], go: "summary" },
          { h: "3. バックアップを保存", p: ["「設定」で「バックアップを保存」を押し、ファイルをクラウドやパソコンに保存します。1か月以上保存していないと「やること」に出ます。"], go: "settings" },
        ] },
      { id: "yearend", title: "年末にやること（12月〜翌1月）", time: "約1時間",
        items: [
          { h: "1. 決算チェックリスト", p: ["「決算書・申告準備」の一番上に10項目あります。上から順に確認します。「自動」の項目は帳簿から自動でチェックされます。"], go: "filing" },
          { h: "2. 固定資産", p: ["今年買った10万円以上のパソコンやカメラは「＋ 固定資産を登録」。減価償却は自動で計算され経費に入ります。"], go: "filing" },
          { h: "3. 貸借対照表（青色65万・55万円の人）", steps: ["12月31日の残高は自動で計算されるので入力不要です。", "通帳と手元の現金を見て、同じなら何もしなくてOK。違えば「実際の残高」に正しい金額を入れます。", "下に「貸借一致 ✓」が出れば完了。今年の期末残高は来年の期首残高に自動で引き継がれます。"], go: "filing" },
          { h: "4. 申告前チェック", p: ["ページの一番下に、要修正（赤）・要確認（黄）・参考（青）の項目が出ます。赤は直してから申告。「該当を表示」でその記帳だけが表示されます。"], go: "filing" },
        ] },
      { id: "return", title: "確定申告（2月16日〜3月15日）", time: "約1〜2時間",
        items: [
          { h: "準備するもの", table: [["マイナンバーカードと暗証番号", "e-Tax で送信するとき"], ["国民年金・国民健康保険の支払い証明", "社会保険料控除"], ["生命保険・地震保険の控除証明書", "保険料控除"], ["医療費の領収書、ふるさと納税の受領証", "医療費控除・寄附金控除"], ["支払調書や報酬明細（源泉徴収されたとき）", "源泉徴収税額"]] },
          { h: "1. 「確定申告ナビ」に控除を入力", p: ["証明書の金額を入れると、納める税金（または戻る税金）と、住民税・個人事業税の見込みがすぐ表示されます。"], go: "return" },
          { h: "2. e-Tax 転記表で作成コーナーに入力", steps: ["「確定申告ナビ」の「確定申告書等作成コーナーを開く」を押します。", "「作成開始」→ e-Tax（マイナンバーカード方式）→「決算書・収支内訳書」。", "アプリの「転記表」を上から順に入力。数字の横の「コピー」でそのまま貼り付けられます。", "決算書を保存したら「所得税」へ。控除を入力し、所得金額がアプリと同じか確認します。", "マイナンバーカードで送信。納付は振替納税（口座引落し）が便利です。"], go: "return" },
          { h: "3. 消費税（インボイス登録をした人）", p: ["「消費税の申告」で3つの質問に答えると、方法ごとの税額を比べます。上に「〇〇にすると安くなります」と出たら「この方式にする」を押し、下の手順で作成コーナーから申告します。期限は3月31日です。"], go: "ctax" },
          { h: "4. 期限をカレンダーに入れる", p: ["ダッシュボードの「今後の期限」で「カレンダーに追加（.ics）」を押すと、申告・納付・住民税・個人事業税の日付がスマホのカレンダーに入り、7日前と前日に通知されます。"], go: "summary" },
        ] },
      { id: "help", title: "困ったとき", time: "必要なとき",
        items: [
          { h: "よくある質問", table: [["金額や日付を読み間違えた", "確認画面で直す。記帳済みなら仕訳帳でその行を開いて修正"], ["どの科目かわからない", "科目を選ぶと下に説明。「取引登録」ページの一番下に科目の一覧"], ["レシートに登録番号がない", "お店が免税事業者だと載っていません。2割特例・簡易課税なら税額に影響しません"], ["「会計コアが古い版です」と出る", "Supabase の SQL Editor で supabase/002_accounting_core.sql を実行"], ["スマホを替えた", "同じアカウントでログインすればすべて見られます"], ["作成コーナーと税額が違う", "アプリの税額は見込みです。作成コーナーの計算が正式です"]] },
          { h: "ご注意", p: ["アプリの税額はすべて見込みで、正式な金額は国税庁の作成コーナーの計算です。個別の判断は国税庁の案内や税理士にご確認ください。"] },
        ] },
    ],
  },
  en: {
    title: "How to use: the complete walkthrough",
    lead: "No accounting knowledge needed. Work down this page and you will get from your first receipt all the way to the tax return. The app does almost all of the bookkeeping and tax arithmetic; your part is photographing receipts, checking them, and filing once a year.",
    year: { title: "The year at a glance", rows: [["Every day", "Photograph receipts, issue invoices (chapter 3)"], ["Once a month", "Import bank and card statements, check the to-do list, save a backup (chapter 4)"], ["December–January", "Year-end: fixed assets, balance sheet, checklist (chapter 5)"], ["16 Feb – 15 Mar", "Tax return; consumption tax by 31 Mar (chapter 6)"]] },
    chapters: [
      { id: "basics", title: "Accounting basics (5 minutes)", time: "Read once", lead: "Know these few words and every page of the app makes sense.",
        items: [
          { h: "Why keep books?", p: ["Every year a sole proprietor tells the tax office how much they earned. Tax is worked out from sales − expenses = income, so every amount in and out is recorded: that is bookkeeping. The more complete it is, the more expenses you can claim and the less tax you pay."] },
          { h: "Sales, expenses, income", table: [["Sales (売上)", "Money earned from work: fees, sales of goods"], ["Expenses (経費)", "Money spent for work: computer accessories, fares, phone"], ["Income (所得)", "Sales − expenses. Tax is calculated from this"]] },
          { h: "Journal entries: two sides of every transaction", p: ["Every transaction has two sides: what the money went to (left, debit) and where it came from (right, credit). Buy ¥1,100 of stationery with your own money: left 消耗品費 1,100, right 事業主借 1,100.", "**The app writes these for you.** You only check that the account is right."] },
          { h: "事業主借 and 事業主貸", p: ["Personal and business money often mix. Paying a business cost with personal money or a personal card is 事業主借 (borrowed from yourself, nothing to repay). Using business money for living costs is 事業主貸. Without a business card, almost every receipt is paid by 事業主借, which is the app's default."] },
          { h: "Business share (家事按分)", p: ["Working from home, part of the rent, electricity and internet is for work and part for living. Only the work share is an expense, e.g. rent 30%. Enter it as the business share; the same shop gets the same share next time."] },
          { h: "Fixed assets and depreciation", p: ["Things of ¥100,000 or more that last several years (computers, cameras) cannot be expensed at once; the cost is spread over several years. That is depreciation. The app asks you to register them and calculates it. On a blue return, items under ¥300,000 can be expensed in the year of purchase."] },
          { h: "Blue return (青色申告)", p: ["If you filed the blue-return application in advance, keep double-entry books and file by e-Tax, up to ¥650,000 is taken off your income. The app is built around the ¥650,000 requirements."] },
          { h: "Consumption tax and invoices", p: ["With sales of ¥10 million or less and no invoice registration you are tax-exempt and file no consumption tax. Registered businesses file; up to 2026 most can use the 20% special rule (pay 20% of the tax on sales). “T + 13 digits” on a receipt is the shop's registration number."] },
          { h: "Keep receipts for 7 years", p: ["Keep paper receipts for 7 years even after photographing them. Electronic receipts (PDFs, online statements) are kept by saving them in the app."] },
        ] },
      { id: "setup", title: "First-time setup (once, about 10 minutes)", time: "Day one",
        items: [
          { h: "1. Create an account and sign in", steps: ["On the sign-in screen enter your email and a password of 8+ characters.", "Tap “No account yet? Create one”. Use the same details from then on.", "On a phone, “Add to Home Screen” in the browser opens it like an app."] },
          { h: "2. Answer the six setup questions", p: ["They appear on your first sign-in. When unsure, pick the recommended option; change them any time in Settings → “Run setup again”."], steps: ["Trade name or your name.", "How you file: blue return approved and e-Tax → “Blue return ¥650,000”.", "Consumption tax: not registered for invoices → “Tax-exempt”.", "How you pay: personal money or card → the first option (事業主借).", "Working from home: yes → rent and similar are split by business share.", "Balances on 1 January of your first year: 0 if you have no business account."], go: "settings" },
          { h: "3. Register fixed monthly costs", p: ["Rent, phone, internet and subscriptions that are the same every month are recorded automatically once registered."], go: "entry", goLabel: "“Recurring entries” at the bottom of New transaction" },
          { h: "4. Issuing invoices? Fill in your details", p: ["At the bottom of Invoices, enter your name, registration number, address and bank details so they print on every invoice."], go: "invoices" },
        ] },
      { id: "daily", title: "Every day (a minute each time)", time: "Whenever money moves",
        items: [
          { h: "When you spend: photograph the receipt", steps: ["Open Receipts and tap “Take photo” (or choose photos or PDFs, several at once).", "The app reads the date, shop, amount, tax rate and registration number, and suggests an account.", "Check five things: date, amount, account, payment (personal money = 事業主借), business share (lower it for things also used privately).", "Tap “Confirm & post”."], go: "scan" },
          { h: "When a note appears", table: [["Equipment of ¥100,000+", "Register it as a fixed asset with the button"], ["Possible duplicate", "If you photographed the same receipt twice, tap “Remove”"], ["Matches a record from a statement", "Leave it ticked: the receipt is attached to that record, not booked twice"], ["Coloured fields", "Less certain readings; tap to see where they were read"]] },
          { h: "Costs without a receipt", p: ["Train fares, direct-debit subscriptions and so on. In New transaction choose Expense, enter date, amount, supplier and description; the journal entry appears below as you type. Picking an account shows a short explanation under it."], go: "entry" },
          { h: "When you earn: an invoice or a sale", steps: ["Billing a client: Invoices → “+ New invoice” → items and amounts → “Print / PDF” to send → “Issue and record the sale”.", "When the money arrives: open the invoice, enter the date and amount received, tap “Record payment”.", "Paid in cash on the spot: record a Sale in New transaction."], go: "invoices" },
        ] },
      { id: "monthly", title: "Every month (about 15 minutes)", time: "Start of the month",
        items: [
          { h: "1. Import bank and card statements", steps: ["Download last month's CSV from your online bank or card company.", "In Statement import choose the type and the account it was paid from (personal card = 事業主借), then the file.", "Lines already booked show “Matches a record” and are not booked again. Tick only the work items among “Not recorded”, check the accounts and record them.", "ATM withdrawals, taxes and card bills are personal and not recorded."], go: "bank" },
          { h: "2. Check the Dashboard to-do list", p: ["Recurring entries to confirm, expenses of ¥100,000+, expenses without a supplier, overdue invoices and so on. “Open” takes you to the right place."], go: "summary" },
          { h: "3. Save a backup", p: ["In Settings tap “Save backup” and keep the file in cloud storage or on a computer. After a month without one, the to-do list reminds you."], go: "settings" },
        ] },
      { id: "yearend", title: "Year end (December – January)", time: "About an hour",
        items: [
          { h: "1. Year-end checklist", p: ["At the top of Year-end & filing there are ten items. Go from top to bottom; automatic items are ticked from the books."], go: "filing" },
          { h: "2. Fixed assets", p: ["Computers, cameras and other items of ¥100,000+ bought this year: “+ Register a fixed asset”. Depreciation is calculated and booked as an expense."], go: "filing" },
          { h: "3. Balance sheet (blue return ¥650,000 / ¥550,000)", steps: ["The 31 December balances are calculated for you; nothing to type.", "Compare with your bank book and cash: if they match, you are done; if not, enter the real figures under “Actual balance”.", "“Balanced ✓” below the table means it is complete. This year's closing balances become next year's opening balances automatically."], go: "filing" },
          { h: "4. Pre-filing check", p: ["The bottom of the page lists items to fix (red), check (yellow) or note (blue). Fix red items before filing; “Show them” lists the records concerned."], go: "filing" },
        ] },
      { id: "return", title: "Tax return (16 February – 15 March)", time: "1–2 hours",
        items: [
          { h: "Have these ready", table: [["My Number card and its PIN", "To submit by e-Tax"], ["Pension and national health insurance payment records", "Social insurance deduction"], ["Life and earthquake insurance certificates", "Insurance deductions"], ["Medical receipts, furusato nōzei receipts", "Medical and donation deductions"], ["Payment statements (if tax was withheld from fees)", "Withheld tax"]] },
          { h: "1. Enter deductions in the Tax return guide", p: ["Type the amounts from your certificates; the page shows the tax to pay or get back, plus resident and business tax estimates."], go: "return" },
          { h: "2. Fill in the 作成コーナー with the e-Tax sheet", steps: ["In the Tax return guide tap “Open 確定申告書等作成コーナー”.", "作成開始 → e-Tax (My Number card) → 決算書・収支内訳書.", "Type the app's figures from top to bottom; “Copy” next to each number pastes it straight in.", "Save the statement, go to 所得税, enter the deductions and check the income matches the app.", "Submit with your My Number card; paying by 振替納税 (direct debit) is easiest."], go: "return" },
          { h: "3. Consumption tax (registered businesses)", p: ["Answer three questions in Consumption tax and the methods are compared. If a banner says another method is cheaper, tap “Use this method”, then follow the steps below it in the 作成コーナー. The deadline is 31 March."], go: "ctax" },
          { h: "4. Put the deadlines in your calendar", p: ["In “Coming deadlines” on the Dashboard tap “Add to calendar (.ics)”: filing and payment dates for income, resident and business tax go into your phone calendar with reminders 7 days and 1 day before."], go: "summary" },
        ] },
      { id: "help", title: "When something goes wrong", time: "As needed",
        items: [
          { h: "Common questions", table: [["Amount or date read wrongly", "Fix it on the confirmation screen; for a posted record, open it in the journal"], ["Not sure which account", "An explanation appears under the account picker; the full list is at the bottom of New transaction"], ["No registration number on the receipt", "Tax-exempt shops have none; under the 20% rule or simplified taxation it does not affect the tax"], ["Banner: accounting core is outdated", "Run supabase/002_accounting_core.sql in Supabase's SQL Editor"], ["New phone", "Sign in with the same account and everything is there"], ["Tax differs from the 作成コーナー", "The app's figures are estimates; the 作成コーナー is final"]] },
          { h: "Please note", p: ["All tax figures in the app are estimates; the NTA's 作成コーナー calculation is final. For your own case, follow NTA guidance or ask a tax accountant (税理士)."] },
        ] },
    ],
  },
};
